site_name: Afendar Documentation
site_description: Technical documentation for Afendar projects
site_author: Afendar
site_url: http://afendar-docs.local

theme: 
  name: material
  favicon: images/favicon.ico
  logo: images/logo.png
  language: fr

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Mode sombre

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Mode clair 

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
- Accueil: 
    - Présentation: index.md
    - Installation: install.md
    - Configuration: configuration.md
- API:
    - Présentation: api/index.md
- Administration:
    - Présentation: admin/index.md
- Front:
    - Présentation: front/index.md
- Bugs:
    - Présentation: bugs/index.md